#+TITLE: "Roguebots" project
#+DESCRIPTION: Work progress, plans, ideas

* TODO Idea
*Roguebots* is a roguelike game with mechanics deeply inspired by [[https://en.m.wikipedia.org/wiki/Robots_(computer_game)][Robots]] game (aka "Gnome Robots", "Daleks", e.t.c). Player walks through the levels of giant tower to find & destroy the Mainframe - a mighty overmind of the Swarm of the Evil Robots. On each floor of the tower a hordes of robots will try to stop an invader, but wisdom and tactics, and also a couple tech gadgets will help you - a well-trained member of the anti-robot rebel - to complete the task and save the humanity!
* TODO View
In the beginning a whole level will fit to screen and no scrolling will needed to show them. And maybe this restriction will stay up to the "release" (if any will be).

First version will work in the ASCII mode, and will support a graphical tiles in the future. Maybe an ASCII mode will be rendered with graphical context (with using SDL or even Gloss), or even will use the browser as a canvas (if a game will be implemented in Elm/GHCJS/PureScript). 
** HUD
- powerups (with defined hotkeys)
  - number of available teleports (both kinds)
- overal time (maybe this must present only in some info/stats screen)
- level number
- some timers and gauges (boss health, factory cooldown)
- summary (union) of all active robots's FOVs if any walls present on level map (this make sence for stealth play style)
* IN-PROGRESS Gameplay
Some sort of tutorial level or even a couple of ones maybe will be needed.
** Level generation
- simple rectangular rooms
- portals on the edges
  - one way portals
- walls and fences (robots can see through last ones bun not through the formes ones)
** Powerups
- original ones
  - random teleport
  - safe teleport
- stealth/visibility
  - invisibility
  - smoke grenades (for slealth)
  - holografic decoys
  - *scanner*
- weapons
  - mines (can kill the player, have some proximity range and damage range)
** Level goals and conditions
*** To complete level PC need to (one of?)
- eliminate all of the enemies
- defeate the boss
- find a key(s)
*** Question: exit portal vs auto teleport after the goal will be reached (classical)?
Exit portal can be useful, when PC will need to collect some powerups.
** mechanics
- robots must see the player to move to
- player must see the robots
  - player can have some sort of *scanner*, which shows all of then robots on the level if they are aggressive 
(see player and hunting him). Scanner do this by hacking of mainframe's alert network.
** TODO enemies
- simple robots, which
  - move straight to the player when see him,
  - kill him on collision,
  - die when collide with other robots, walls, etc 
- robots with limited range of possible directions to move to (moving only horizontally, vertically, ...)
- sleeping robots which sleep in the beginning, and wake up when PC moved near them (robots stays unseen until that)
- mine droppers
- robot fabrics
  - spawn the robots with constant rate
  - can be destroyed by other robots, mines, etc

* Roadmap:
- [ ] minimal app which can draw the view (ASCII version)
- [ ] original mechanics, w/o multiple levels, visibility, disposable items, robots other than original ones
- [ ] ...
